[project]
name = "nano-llms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.1",
    "jaxtyping>=0.3.3",
    "numpy>=2.3.4",
    "regex>=2025.10.23",
    "tqdm>=4.67.1",
]
